
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class AplikasiPengitunganKata extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPengitunganKata
     */
    public AplikasiPengitunganKata() {
        initComponents();
        
     jTextArea1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
    @Override
    public void insertUpdate(javax.swing.event.DocumentEvent e) {
        updateCounts();
    }

    @Override
    public void removeUpdate(javax.swing.event.DocumentEvent e) {
        updateCounts();
    }

    @Override
    public void changedUpdate(javax.swing.event.DocumentEvent e) {
        updateCounts();
    }
});

    }  
    
   private void updateCounts() {
    // Ambil teks dari JTextArea
        String text = jTextArea1.getText().trim();
        
        // Menghitung jumlah kata
        String[] words = text.split("\\s+");
        int wordCount = text.isEmpty() ? 0 : words.length;
        
        // Menghitung jumlah kalimat
        String[] sentences = text.split("[.!?]+\\s*");
        int sentenceCount = (text.isEmpty() || sentences.length == 0) ? 0 : 
                (int) java.util.Arrays.stream(sentences).filter(s -> !s.trim().isEmpty()).count();
        
        // Menghitung jumlah paragraf
        String[] paragraphs = text.split("\n+");
        int paragraphCount = (text.isEmpty() || paragraphs.length == 0) ? 0 : 
                (int) java.util.Arrays.stream(paragraphs).filter(p -> !p.trim().isEmpty()).count();

        // Menampilkan hasil ke JLabel
        txtKata.setText("Jumlah Kata: " + wordCount);
        txtKalimat.setText("Jumlah Kalimat: " + sentenceCount);
        txtParagraf.setText("Jumlah Paragraf: " + paragraphCount);
    
}
   
   private void searchWord() {
    String text = jTextArea1.getText().toLowerCase();  // Mengambil teks dari JTextArea dan mengubahnya ke huruf kecil
    String searchWord = lblCari.getText().toLowerCase().trim();  // Mengambil kata pencarian dari JTextField dan mengubahnya ke huruf kecil
    
    // Validasi jika JTextField kosong
    if (searchWord.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Kata pencarian tidak boleh kosong.");
        return;
    }
    
    // Menghitung kemunculan kata
    int count = 0;
    int index = text.indexOf(searchWord);
    
    while (index != -1) {
        count++;
        index = text.indexOf(searchWord, index + searchWord.length());
    }
    
    // Menampilkan hasil ke JLabel
    txtCari.setText("Jumlah kata '" + searchWord + "': " + count);
}
   
   private void simpanKeFile() {
    // Pilih file menggunakan JFileChooser
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    int option = fileChooser.showSaveDialog(this);
    
    if (option == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File file = fileChooser.getSelectedFile();
        
        try (java.io.FileWriter writer = new java.io.FileWriter(file)) {
            // Ambil teks dari JTextArea
            String text = jTextArea1.getText();
            
            // Ambil hasil perhitungan
            String wordCount = txtKata.getText();
            String sentenceCount = txtKalimat.getText();
            String paragraphCount = txtParagraf.getText();
            
            // Tulis ke file
            writer.write("Teks:\n");
            writer.write(text + "\n\n");
            writer.write("Hasil Perhitungan:\n");
            writer.write(wordCount + "\n");
            writer.write(sentenceCount + "\n");
            writer.write(paragraphCount + "\n");
            
            // Beri tahu pengguna bahwa file berhasil disimpan
            JOptionPane.showMessageDialog(this, "File berhasil disimpan: " + file.getAbsolutePath());
        } catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan file.");
        }
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnHitung = new javax.swing.JButton();
        lblCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        txtKata = new javax.swing.JLabel();
        txtKalimat = new javax.swing.JLabel();
        txtParagraf = new javax.swing.JLabel();
        txtCari = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtKata.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtKata.setForeground(new java.awt.Color(240, 240, 240));

        txtKalimat.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtKalimat.setForeground(new java.awt.Color(240, 240, 240));

        txtParagraf.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtParagraf.setForeground(new java.awt.Color(240, 240, 240));

        txtCari.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtCari.setForeground(new java.awt.Color(240, 240, 240));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("APLIKASI PENGHITUNG KATA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCari, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari)
                            .addComponent(btnHitung)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus)
                            .addComponent(btnKeluar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKata)
                            .addComponent(txtKalimat)
                            .addComponent(txtParagraf)
                            .addComponent(txtCari)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCari, btnHapus, btnHitung, btnKeluar, btnSimpan});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnCari)
                        .addGap(18, 18, 18)
                        .addComponent(btnHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnKeluar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtKata)
                        .addGap(18, 18, 18)
                        .addComponent(txtKalimat)
                        .addGap(18, 18, 18)
                        .addComponent(txtParagraf)
                        .addGap(18, 18, 18)
                        .addComponent(txtCari)))
                .addGap(161, 161, 161))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        updateCounts();
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        searchWord();
    
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
         simpanKeFile();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        lblCari.setText("");
        txtKata.setText("");
        txtKalimat.setText("");
        txtParagraf.setText("");
        txtCari.setText("");
        jTextArea1.setText("");
        lblCari.requestFocus();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPengitunganKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPengitunganKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPengitunganKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPengitunganKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPengitunganKata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lblCari;
    private javax.swing.JLabel txtCari;
    private javax.swing.JLabel txtKalimat;
    private javax.swing.JLabel txtKata;
    private javax.swing.JLabel txtParagraf;
    // End of variables declaration//GEN-END:variables
}
